// Mocks generated by Mockito from annotations
// in mediflow/test/mocks/repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:mediflow/features/auth/domain/auth_repository.dart' as _i4;
import 'package:mediflow/features/clinic/domain/app_enums.dart' as _i6;
import 'package:mediflow/features/clinic/domain/clinic_repository.dart' as _i7;
import 'package:mediflow/features/clinic/domain/clinic_snapshot.dart' as _i3;
import 'package:mediflow/features/clinic/domain/entities.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClinicUser_0 extends _i1.SmartFake implements _i2.ClinicUser {
  _FakeClinicUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClinicSnapshot_1 extends _i1.SmartFake
    implements _i3.ClinicSnapshot {
  _FakeClinicSnapshot_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppointment_2 extends _i1.SmartFake implements _i2.Appointment {
  _FakeAppointment_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ClinicUser> login(
    String? email,
    String? password,
    _i6.UserRole? demoRole,
  ) => (super.noSuchMethod(
    Invocation.method(#login, [email, password, demoRole]),
    returnValue: _i5.Future<_i2.ClinicUser>.value(
      _FakeClinicUser_0(
        this,
        Invocation.method(#login, [email, password, demoRole]),
      ),
    ),
  ) as _i5.Future<_i2.ClinicUser>);

  @override
  _i5.Future<_i2.ClinicUser> register(_i4.RegistrationInput? input) =>
      (super.noSuchMethod(
        Invocation.method(#register, [input]),
        returnValue: _i5.Future<_i2.ClinicUser>.value(
          _FakeClinicUser_0(this, Invocation.method(#register, [input])),
        ),
      ) as _i5.Future<_i2.ClinicUser>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);
}

/// A class which mocks [ClinicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClinicRepository extends _i1.Mock implements _i7.ClinicRepository {
  MockClinicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ClinicSnapshot> load() => (super.noSuchMethod(
    Invocation.method(#load, []),
    returnValue: _i5.Future<_i3.ClinicSnapshot>.value(
      _FakeClinicSnapshot_1(this, Invocation.method(#load, [])),
    ),
  ) as _i5.Future<_i3.ClinicSnapshot>);

  @override
  _i5.Stream<_i3.ClinicSnapshot> watch() => (super.noSuchMethod(
    Invocation.method(#watch, []),
    returnValue: _i5.Stream<_i3.ClinicSnapshot>.empty(),
  ) as _i5.Stream<_i3.ClinicSnapshot>);

  @override
  _i5.Future<void> registerUser(_i2.ClinicUser? user, {_i2.Doctor? doctor}) =>
      (super.noSuchMethod(
        Invocation.method(#registerUser, [user], {#doctor: doctor}),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> bookAppointment(_i2.Appointment? appointment) =>
      (super.noSuchMethod(
        Invocation.method(#bookAppointment, [appointment]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Appointment> changeAppointmentStatus({
    required _i2.ClinicUser? actor,
    required String? appointmentId,
    required _i6.AppointmentStatus? expected,
    required _i6.AppointmentStatus? target,
  }) => (super.noSuchMethod(
    Invocation.method(#changeAppointmentStatus, [], {
      #actor: actor,
      #appointmentId: appointmentId,
      #expected: expected,
      #target: target,
    }),
    returnValue: _i5.Future<_i2.Appointment>.value(
      _FakeAppointment_2(
        this,
        Invocation.method(#changeAppointmentStatus, [], {
          #actor: actor,
          #appointmentId: appointmentId,
          #expected: expected,
          #target: target,
        }),
      ),
    ),
  ) as _i5.Future<_i2.Appointment>);
}
